library 'pipeline-library'
pipeline {
  agent none
  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 10)
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
    repository = "${repository}"
  }
  stages('React Test and Build')
  {
    stage('React Tests') {
      agent {
        kubernetes {
          label 'nodejs'
       }
      }
      steps {
            checkout scm           
            container('nodejs') {
              readCache 'npm-cache'
              sh '''
                 npm install
                 '''
              writeCache includes: 'npm_modules', name: 'npm-cache'
            }
      } 
    }
    stage('Build and Push Image') {
      when {
        beforeAgent true
        anyOf {
          branch 'main';
          branch 'master'
        }
      }
      steps { 
        kanikoBuildPushGeneric("${repository}", "latest", "${gcpProject}/${repoOwner}")
        {
          checkout scm
        }
      }
    } 
  }
}
